site_name: Mini Babel Library
site_url: https://ruoxining.github.io/OBvault
repo_url: https://github.com/ruoxining/OBvault
repo_name: OBvault

nav:
  - 'index.md' 
  - ğŸ’»CSä¸“æ : 
    - ç´¢å¼•: 'CS/index.md'
    - Cå¤§ç¨‹libgraphics: 'CS/libgraphics.md'
    - C++æŒç»­è¿›æ­¥: 
      - ZJUå¬è¯¾: 'CS/CPP/course.md'
      - ZJUæœŸæœ«å¤ä¹ : 'CS/CPP/final_review.md'
    - x86æ±‡ç¼–: 'CS/x86assm.md'
    - OSæ“ä½œç³»ç»Ÿ:
      - index: 'CS/OS/index.md'
      - lab: 'CS/OS/lab.md'
    - CAä½“ç³»ç»“æ„:
      - Index: 'CS/CA/index.md'
      - chap2: 'CS/CA/chap2.md'
      - chap3: 'CS/CA/chap3.md'
      - chap5: 'CS/CA/chap5.md'

  - ğŸ“DLä¸“æ : 
    - ç´¢å¼•: 'DL/index.md'
    - NLP Theory: 
      - Explainable NLP: 'DL/NLPTheory/explainable_nlp.md'
      - Math Word Problem: 'DL/NLPTheory/mwp.md'

  - ğŸŒ³Lingä¸“æ :
    - ç´¢å¼•: 'Ling/index.md'
    - å¥æ³•å­¦Syntax: 
      - Index: 'Ling/Syntax/index.md'
      - è½¬æ¢ç”Ÿæˆå¥æ³•: 'Ling/Syntax/conv_gen.md'
      - æ™®éè¯­æ³•: 'Ling/Syntax/uni_gram.md'
      - ä¾å­˜å¥æ³•UD&SUD: 'Ling/Syntax/ud_sud.md'
    - è¯­ä¹‰å­¦Semantics: 
      - Index: 'Ling/Semantics/index.md'
      - Definition Clearification: 'Ling/Semantics/definitions.md'
      - Logics & Formal Semantics: 'Ling/Semantics/formal_semantics.md'
      - Scope Ambiguity: 'Ling/Semantics/ambiguity.md'
    - è¯­ç”¨å­¦Pragmatics:
      - Introduction: 'Ling/Pragmatics/intro.md'
      - Theory&Hypothesis: 'Ling/Pragmatics/theories.md'
      - Sociopragmatics: 'Ling/Pragmatics/socio.md'
      - Research Methods: 'Ling/Pragmatics/ca_da.md'
    - è¯­è¨€å“²å­¦Philosophy of Language: 'Ling/pol_zh.md'

  - ğŸ’­è¯´çè¯äº†: 
    - ç´¢å¼•: 'Other/index.md'
    - æˆ‘çš„å·¥å…·ç®±ï¼: 'Other/tools.md'
    - DL & NLP èµ„æºæ•´ç†: 'Other/nlp_resources.md'
    - WhyNote: 'Other/whynote.md'
    - Portfolio: 'Other/portfolio.md'
    - 24fallç”³è¯·è®°å½•: 'Other/24fall.md' 
    - è‹±ä¸“è½¬CS&NLPæŒ‡åŒ—: 'Other/zju_ling_cs.md'
    - NLPç”³è¯·PhDç»éªŒ(æ¬è¿): 'Other/nlp_phd.md'


theme:
  name: material
  palette:
    primary: black
  language: zh
  features:
    - content.code.copy
    - navigation.expand
    - navigation.top
  icon:
    repo: fontawesome/brands/git-alt
plugins:
  - search
  # - mkdocs-video:
  #     is_video: True
  #     video_muted: True
  #     video_controls: True
  #     css_style:
  #       width: "50%"
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - _css/style.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/tex-mml-chtml.js