site_name: MiniBabelLibrary
site_url: https://ruoxining.github.io/OBvault
repo_url: https://github.com/ruoxining/OBvault
repo_name: OBvault

nav:
  - 'index.md' 
  - ç”³è¯·å¿ƒå¾—: 
    - ç´¢å¼•: 'App/index.md'
    - 24fallç”³è¯·è®°å½•: 'App/24fall.md' 
    - è‹±ä¸“è½¬CS&NLPæŒ‡åŒ—: 'App/zju_ling_cs.md'
    - NLPç”³è¯·PhDç»éªŒ(æ¬è¿): 'App/nlp_phd.md'

  - CSä¸“æ : 
    - ç´¢å¼•: 'CS/index.md'
    - Cè¯­æ³•: 'CS/c_lang.md'
    - Cå¤§ç¨‹libgraphicsä½¿ç”¨è®°å½•: 'CS/libgraphics.md'
    - ç¼–ç¨‹è§„èŒƒæ–‡æ¡£æ¨¡æ¿: 'CS/coding_code.md'
    - C++æŒç»­è¿›æ­¥: 
      - ZJUå¬è¯¾: 'CS/CPP/course.md'
      - ZJUæœŸæœ«å¤ä¹ : 'CS/CPP/final_review.md'
      - ç»§æ‰¿: 'CS/CPP/inheritance.md'
      - æ¨¡æ¿å’Œæ ‡å‡†æ¨¡æ¿åº“: 'CS/CPP/templates.md'
      - ç±»å‹å’Œç±»å‹è½¬æ¢: 'CS/CPP/type.md'
      - æ–‡ä»¶è¯»å†™: 'CS/CPP/file_io.md'
      - æµ…æ‹·è´å’Œæ·±æ‹·è´: 'CS/CPP/copy.md'
      - å‘½åç©ºé—´: 'CS/CPP/namespace.md'
    - x86æ±‡ç¼–: 'CS/x86assm.md'
    - OSæ“ä½œç³»ç»Ÿ: 
      - ç´¢å¼•: 'CS/OS/index.md'
      - è¯¾ç¨‹å¼•å…¥: 'CS/OS/overview.md'
      - è¿›ç¨‹ä¸åŒæ­¥: 'CS/OS/process_syn.md'
      - å†…å­˜å’Œæ–‡ä»¶ç³»ç»Ÿ: 'CS/OS/mem_file.md'
    - Objdumpå·¥å…·: 'CS/objdump.md'
    - å†™ä¸ªçˆ¬è™«CrawlerğŸ•·ï¸ï¼: 'CS/crawler.md'

  - DLä¸“æ : 
    - ç´¢å¼•: 'DL/index.md'
    - NLP Theory: 
      - E.Bender Ling4NLPè¯»ä¹¦ç¬”è®°: 'DL/NLPTheory/ling_ebender.md'
      - CoT Prompt: 'DL/NLPTheory/cot.md'
      - NLI: 'DL/NLPTheory/nli.md'
      - Embodied AI: 'DL/NLPTheory/embodied_ai.md'
      - Explainable NLP: 'DL/NLPTheory/explainable_nlp.md'
      - Math Word Problem: 'DL/NLPTheory/mwp.md'
      - Neural Symbolic AI: 'DL/NLPTheory/neural_symbolic.md'
      - Autoregressive Decoder: 'DL/NLPTheory/autoregressive.md'
    - NLP Tech:
      - MLå…«è‚¡: 'DL/NLPTech/ml_cheatsheet.md'
      - Transformerä»£ç : 'DL/NLPTech/transformer_code.md'
      - BERTä»£ç : 'DL/NLPTech/bert_code.md'
      - GPTä»£ç : 'DL/NLPTech/gpt_code.md'
      - LLaMaä»£ç : 'DL/NLPTech/llama_code.md'
      - CS231nç¬”è®°(è¿˜æ²¡å†™): 'DL/NLPTech/cs231n.md'
      - CS224nç¬”è®°(è¿˜æ²¡å†™): 'DL/NLPTech/cs224n.md'
      - è§„åˆ™æå–æ–‡æœ¬æ ¼å¼æ€»ç»“: DL/NLPTech/rule_text.md
    - Pythonç”¨æ³•é€ŸæŸ¥:
      - IPDB: 'DL/Python/ipdb.md'
      - Pandas DFé€ŸæŸ¥: 'DL/Python/pandas_dataframe.md'
      - Pythoné¢å‘å¯¹è±¡è¯­æ³•: 'DL/Python/python_object.md'
      - Python Setup Packages: 'DL/Python/setup_pack.md'
      - Pytorché€ŸæŸ¥: 'DL/Python/pytorch.md'
      - Broadcastble Vector: 'DL/Python/broadcastable_vector.md'
    - å‘½ä»¤è¡Œç”¨æ³•é€ŸæŸ¥: 
      - Anacondaé€ŸæŸ¥: 'DL/Terminal/anaconda.md'
      - Linuxå‘½ä»¤è¡Œ: 'DL/Terminal/linux.md'
      - Pytorchå‘½ä»¤è¡Œ: 'DL/Terminal/pytorch_terminal.md'
      - tmuxé€ŸæŸ¥: 'DL/Terminal/tmux.md'

  - Lingä¸“æ :
    - ç´¢å¼•: 'Ling/index.md'
    - è¯­éŸ³å­¦Phonetics:
      - Reduction in verb.+prep.: 'Ling/Phonetics/reduction.md'
      - Signal Basis: 'Ling/Phonetics/signal.md'
    - å¥æ³•å­¦Syntax: 
      - è½¬æ¢ç”Ÿæˆå¥æ³•: 'Ling/Syntax/conv_gen.md'
      - æ™®éè¯­æ³•: 'Ling/Syntax/uni_gram.md'
      - ä¾å­˜å¥æ³•UD&SUD: 'Ling/Syntax/ud_sud.md'
    - è¯­ä¹‰å­¦Semantics: 
      - Index: 'Ling/Semantics/index.md'
      - Definition Clearification: 'Ling/Semantics/definitions.md'
      - Logics & Formal Semantics: 'Ling/Semantics/formal_semantics.md'
      - Scope Ambiguity: 'Ling/Semantics/ambiguity.md'
    - è¯­ç”¨å­¦Pragmatics:
      - Research Methods: 'Ling/Pragmatics/ca_da.md'
    - è¯­è¨€å“²å­¦Philosophy of Language: 'Ling/pol_zh.md'
    
  - Mathä¸“æ : 
    - ç´¢å¼•: 'Math/index.md'
    - å›¾è®º: 'Math/Graph/laplace_matrix.md'
    - é›¶æ•£çš„é¢˜: 'Math/questions.md'
    - å„ç§Normal Forms: 'Math/normal_forms.md'

  - è¯´çè¯äº†: 
    - ç´¢å¼•: 'Other/index.md'
    - æˆ‘çš„å·¥å…·ç®±ï¼: 'Other/tools.md'
    - APA Format: 'Other/apa.md'
    - DL & NLP èµ„æºæ•´ç†: 'Other/nlp_resources.md'
    - Portfolio: 'Other/portfolio.md'



theme:
  name: material
  palette:
    primary: black
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   toggle:
    #     icon: material/weather-night
    #     name: æš—è‰²æ¨¡å¼
    # - media: "(prefers-color-scheme: dark)"
    #   primary: black
    #   scheme: slate
    #   toggle:
    #     icon: material/weather-sunny
    #     name: äº®è‰²æ¨¡å¼
  language: zh
  features:
    - content.code.copy
    # - navigation.tabs
    - navigation.expand
    - navigation.top
    # - navigation.sections
  icon:
    repo: fontawesome/brands/git-alt
plugins:
  - search
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - _css/style.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/tex-mml-chtml.js
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
