site_name: MiniBabelLibrary
site_url: https://ruoxining.github.io/OBvault
repo_url: https://github.com/ruoxining/OBvault
repo_name: OBvault

nav:
  - 'index.md'
  - ç”³è¯·å¿ƒå¾—: 
    - ç´¢å¼•: 'Application/index.md'
    - 24fallç”³è¯·è®°å½•: 'Application/ã€TODOã€‘æˆ‘çš„24fallç”³è¯·è®°å½•.md' 
    - è‹±ä¸“è½¬CS&NLPæŒ‡åŒ—: 'Application/ZJU English Major to CS&NLP.md'
    - æ¬è¿NLPç”³è¯·PhDç»éªŒ: 'Application/NLP Global PHD Equality Digest.md'
  - CSä¸“æ : 
    - ç´¢å¼•: 'CS_Notes/index.md'
    - C++æŒç»­è¿›æ­¥: 
      - ZJUå¬è¯¾: 'CS_Notes/æˆ‘çš„C++å­¦ä¹ è®°å½•/å¬è¯¾ï¼ˆZJU & Stanford CS106Bï¼‰.md'
      - ZJUæœŸæœ«å¤ä¹ : 'CS_Notes/æˆ‘çš„C++å­¦ä¹ è®°å½•/ZJU æœŸæœ«å¤ä¹ .md'
      - ç»§æ‰¿: 'CS_Notes/æˆ‘çš„C++å­¦ä¹ è®°å½•/ç»§æ‰¿ Inheritance.md'
      - æ¨¡æ¿å’Œæ ‡å‡†æ¨¡æ¿åº“: 'CS_Notes/æˆ‘çš„C++å­¦ä¹ è®°å½•/æ¨¡æ¿å’Œæ ‡å‡†æ¨¡æ¿åº“ Template & STL.md'
      - ç±»å‹å’Œç±»å‹è½¬æ¢: 'CS_Notes/æˆ‘çš„C++å­¦ä¹ è®°å½•/ç±»å‹å’Œç±»å‹è½¬æ¢Type & Type Conversion.md'
      - æ–‡ä»¶è¯»å†™: 'CS_Notes/æˆ‘çš„C++å­¦ä¹ è®°å½•/æ–‡ä»¶è¯»å†™ File IO.md'
      - æµ…æ‹·è´å’Œæ·±æ‹·è´: 'CS_Notes/æˆ‘çš„C++å­¦ä¹ è®°å½•/æµ…æ‹·è´å’Œæ·±æ‹·è´ Shallow copy & Deep copy.md'
      - å‘½åç©ºé—´: 'CS_Notes/æˆ‘çš„C++å­¦ä¹ è®°å½•/å‘½åç©ºé—´ Namespace.md'
    - OSæ“ä½œç³»ç»Ÿ: 
      - Index: 'CS_Notes/OSæ“ä½œç³»ç»Ÿ/index.md'
      - å¼•å…¥: 'CS_Notes/OSæ“ä½œç³»ç»Ÿ/Lecture_Overview.md'
      - è¿›ç¨‹ä¸åŒæ­¥: 'CS_Notes/OSæ“ä½œç³»ç»Ÿ/è¿›ç¨‹ä¸åŒæ­¥.md'
      - å†…å­˜/å­˜å‚¨/æ–‡ä»¶ç³»ç»Ÿ: 'CS_Notes/OSæ“ä½œç³»ç»Ÿ/å†…å­˜_å­˜å‚¨_æ–‡ä»¶ç³»ç»Ÿ.md'
    - 8086&80386æ±‡ç¼–: 'CS_Notes/8086&80386æ±‡ç¼–.md'
    - ç¼–ç¨‹è§„èŒƒæ–‡æ¡£æ¨¡æ¿: 'CS_Notes/ç¼–ç¨‹è§„èŒƒæ–‡æ¡£æ¨¡æ¿.md'
    - Cè¯­è¨€: 'CS_Notes/Cè¯­è¨€.md'
    - Cå¤§ç¨‹libgraphicsè¸©å‘æ–‡æ¡£: 'CS_Notes/Cå¤§ç¨‹libgraphicsè¸©å‘æ–‡æ¡£.md'
    - çˆ¬è™«: 'CS_Notes/CrawlerğŸ•·.md'
  - DLä¸“æ : 
    - ç´¢å¼•: 'DL_Notes/index.md'
    - NLP Theory: 
      - CoT prompt: 'DL_Notes/NLP/Chain-of-Thought.md'
      - Contrastive Learning and Interpretability: 'DL_Notes/NLP_Theory/Contrastive Learning and Interpretability.md'
    - NLP Tech:
      - è§„åˆ™æå–æ–‡æœ¬æ ¼å¼ç»éªŒæ€»ç»“: DL_Notes/NLP_Tech/è§„åˆ™æå–æ–‡æœ¬æ ¼å¼ç»éªŒæ€»ç»“.md
    - Pythonç”¨æ³•é€ŸæŸ¥:
      - IPDB: 'DL_Notes/Python_Usage/IPDB.md'
      - Pandas DFé€ŸæŸ¥: 'DL_Notes/Python_Usage/Pandas Dataframeå¸¸ç”¨.md'
      - Pythonç±»é€ŸæŸ¥: 'DL_Notes/Python_Usage/Pythonçš„é¢å‘å¯¹è±¡ä½¿ç”¨æŠ€å·§.md'
      - Pytorché€ŸæŸ¥: 'DL_Notes/Python_Usage/Pytorch å¸¸ç”¨å‘½ä»¤.md'
    - å‘½ä»¤è¡Œç”¨æ³•é€ŸæŸ¥: 
      - Anacondaé€ŸæŸ¥: 'DL_Notes/Terminal_Usage/Anacondaå¸¸ç”¨å‘½ä»¤.md'
      - Linuxå‘½ä»¤è¡Œé€ŸæŸ¥: 'DL_Notes/Terminal_Usage/Linux.md'
      - tmuxé€ŸæŸ¥: 'docs/DL_Notes/Terminal_Usage/tmux.md'
  - Linguisticsä¸“æ :
    - Index: 'Linguistics/index.md'
    - Phonetics:
      - Reduction in verb.+prep.: 'Linguistics_Notes/Phonetics/Reduction of Intentional verb+prep.md'
      - Signal Basics: 'Linguistics_Notes/Phonetics/Signal Basics.md'
    - Syntax: 
      - è½¬æ¢ç”Ÿæˆå¥æ³•: 'Linguistics/è½¬æ¢ç”Ÿæˆå¥æ³•.md'
      - ä¹”å§†æ–¯åŸºæ™®éè¯­æ³•: 'Linguistics_Notes/Syntax/Chomskyâ€™s Universal Grammar.md'
      - UDå’ŒSUD: 'docs/Linguistics_Notes/Syntax/UD and SUD.md'
    - Semantics: 
      - Index: 'Linguistics_Notes/Semantics/index.md'
      - Definition Clearification: 'Linguistics_Notes/Semantics/Definition Clearification.md'
      - Logics & Formal Semantics: 'Linguistics_Notes/Semantics/Logics & Formal Semantics.md'
      - Ambiguity: 'Linguistics_Notes/Semantics/Ambiguity.md'
    - Pragmatics: 'index.md'
  - Mathä¸“æ : 
    - ç´¢å¼•: 'Math_Notes/index.md'
    - å›¾è®º: 'Math_Notes/Graph Theory/Laplacian Matrix.md'
    - é›¶æ•£çš„é¢˜: 'Math_Notes/é›¶æ•£çš„é¢˜.md'
  - å…¶å®ƒè¯¾ç¨‹:
    - ç´¢å¼•: 'Other_Courses/index.md' 
    - é’¢ç´æœŸæœ«å¤ä¹ : 'Other_Courses/æ‰“å¼€è‰ºæœ¯ä¹‹é—¨-é’¢ç´æœŸæœ«å¤ä¹ .md'
  - çè¯´ä¸€äº›ä¸œè¥¿: 
    - ç´¢å¼•: 'çè¯´ä¸€äº›ä¸œè¥¿/index.md'
    - å¥½ç”¨çš„å·¥å…·: 'çè¯´ä¸€äº›ä¸œè¥¿/å¥½ç”¨çš„å·¥å…·.md'
    - Notion vs. Obsidian: 'çè¯´ä¸€äº›ä¸œè¥¿/Notionå’ŒObsidianï¼Œé€‰å“ªä¸€ä¸ª.md'
    - ZOTEROç®€ä»‹: 'çè¯´ä¸€äº›ä¸œè¥¿/ZOTERO ç®€ä»‹åŠé…ç½®æ•™ç¨‹.md'



theme:
  name: material
  language: zh
  palette:
    primary: black
    accent: indigo
  feature:
    tabs: true
